CREATE TABLE IF NOT EXISTS REQUESTS (
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    app VARCHAR(64) NOT NULL,
    uri VARCHAR(255) NOT NULL,
    ip VARCHAR(16) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    CONSTRAINT pk_request_id PRIMARY KEY (id)
);