CREATE TABLE IF NOT EXISTS REQUESTS (
    id BIGINT NOT NULL,
    application VARCHAR(64) NOT NULL,
    uri VARCHAR(255) NOT NULL,
    ip VARCHAR(16) NOT NULL,
    created TIMESTAMP NOT NULL,
    CONSTRAINT pk_request_id PRIMARY KEY (id)
);