CREATE TABLE IF NOT EXISTS USERS (
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    email VARCHAR(64) NOT NULL,
    name VARCHAR(64) NOT NULL,
    CONSTRAINT user_id_pk PRIMARY KEY (id),
    CONSTRAINT user_email_uq UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS CATEGORIES (
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    name VARCHAR(256) NOT NULL,
    CONSTRAINT category_id_pk PRIMARY KEY (id),
    CONSTRAINT category_name_uq UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS EVENTS (
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    title VARCHAR(120) NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    description VARCHAR(7000) NOT NULL,
    event_date TIMESTAMP NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    paid BOOLEAN NOT NULL,
    participant_limit INT NOT NULL,
    request_moderation BOOLEAN NOT NULL,
    initiator BIGINT NOT NULL,
    category BIGINT NOT NULL,
    published BOOLEAN NOT NULL,
    published_on TIMESTAMP,
    state VARCHAR(32) NOT NULL,
    created_on TIMESTAMP NOT NULL,
    CONSTRAINT event_id_pk PRIMARY KEY (id),
    CONSTRAINT event_initiator_fk FOREIGN KEY (initiator) REFERENCES USERS (id),
    CONSTRAINT event_category_fk FOREIGN KEY (category) REFERENCES CATEGORIES (id),
    CONSTRAINT event_pl_positive CHECK (participant_limit >= 0)
);

CREATE TABLE IF NOT EXISTS PARTICIPATION_REQUESTS (
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    event_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL,
    created TIMESTAMP NOT NULL,
    CONSTRAINT pr_id_pk PRIMARY KEY (id),
    CONSTRAINT pr_event_id_fk FOREIGN KEY (event_id) REFERENCES EVENTS (id),
    CONSTRAINT pr_requester_id_fk FOREIGN KEY (requester_id) REFERENCES USERS (id)
);

CREATE TABLE IF NOT EXISTS COMPILATIONS (
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    title VARCHAR(64) NOT NULL,
    pinned BOOLEAN NOT NULL,
    CONSTRAINT comp_id_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS COMPILATION_EVENT (
    compilation_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    CONSTRAINT ce_pk PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT ce_comp_id_fk FOREIGN KEY (compilation_id) REFERENCES COMPILATIONS (id),
    CONSTRAINT ce_event_id_fk FOREIGN KEY (event_id) REFERENCES EVENTS (id)
);